### PR TITLE
Don't install linkchecker on python 3 (it's broken)

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by brianhlin** [comment]
Additionally, we probably shouldn't run the linkchecker if it's not installed.

**Comment by matyasselmeci** [comment]
Shouldn't it always be installed in the CI environment? `verify` does nothing other than run linkchecker so if I were to conditionalize it, it wouldn't run anything.

**Comment by brianhlin** [comment]
At the moment it does but if we move to a Python3 CI image, `verify` will fail due to the `linkchecker` being missing.

`verify` also runs `mkdocs serve`, which is important for catching issues with internal links or `mkdocs.yml`.

**Comment by matyasselmeci** [comment]
verify _runs_ mkdocs serve, but does it check that mkdocs serve is working?

**Comment by brianhlin** [comment]
Technically, yes: if `mkdocs serve` fails, the linkchecker has no chance of working

**Comment by matyasselmeci** [comment]
Yes but if we don't run linkchecker, it doesn't give us the indication that mkdocs failed. Perhaps we could stick a few wgets in there?

**Comment by matyasselmeci** [comment]
Better now?

**Review by brianhlin — APPROVED** [review]

**Pull request merged**
